/**:
  ros__parameters:
    node:
      remaining_energy_filter_alpha: 0.5 # 对 remaining_energy_supercap 和 remaining_energy_supercap 进行低通滤波的指数衰减系数 [0,1]
      prediction_horizon_seconds: 2.0 # 代价地图时域融合的预测时间窗口 (0=仅用当前帧)，用于 planner
      prediction_weight_decay: 1.0 # 代价地图时域融合中时域帧权重的线性衰减因子 [0,1]，用于 planner

      topics:
        goal_sub: "/decision/nav_goal"
        global_direction_map_sub: "/map_server/global_direction_map"
        global_cost_map_sub: "/map_server/global_cost_map"
        local_cost_maps_sub: "/map_server/local_cost_maps"
        chassis_status_sub: "/serial_bridge/chassis_status"
        comp_stage_sub: "/serial_bridge/comp_stage"
        spin_cmd_sub: "/decision/spin_cmd"
        global_path_pub: "/nav_executor/global_path"
        chassis_cmd_pub: "/nav_executor/chassis_cmd"
        state_pub: "/nav_executor/state"

      debug:
        enable: true
        final_cost_map_pub_topic: "/nav_executor/debug/final_cost_map"
        rough_path_pub_topic: "/nav_executor/debug/rough_path"
        warmup_path_pub_topic: "/nav_executor/debug/warmup_path"
        search_path_pub_topic: "/nav_executor/debug/search_path"
        mpc_path_pub_topic: "/nav_executor/debug/mpc_path"
        v_pred_pub_topic: "/nav_executor/debug/v_pred"
        w_pred_pub_topic: "/nav_executor/debug/w_pred"
