/**:
  ros__parameters:
    pub_topic: "costmap" # 发布话题名称
    num_threads: 8 # 进行点云分析时启用的线程数
    num_neighbors: 10 # 分析点云法向量时关注的邻居个数
    map_resolution: 0.05 # 代价地图的每格大小，单位m
    map_x_size: 560 # 地图x方向的大小，以格点为单位，坐标系原点在tf的"map"
    map_y_size: 300 # 地图y方向的大小，以格点为单位，坐标系原点在tf的"map"
    dilate_kernel_size: 3 # 对代价地图进行膨胀的核大小
    gaussian_blur_size: 15 # 对代价地图进行高斯模糊的核大小
    gaussian_blur_sigma: 2.0 # 对代价地图进行高斯模糊的标准差

    global_costmap: # 全局先验地图配置
      file_path: "1897translated.pcd" # 可以为图片格式或pcd，如果是图片就直接作为全局地图，pcd就进行点云分析
      file_type_pcd: # 如果以pcd格式读取
        # 如果以pcd格式读取，坐标系xy方向和原点均与点云坐标系一致
        max_z: 0.5 # 关心的z范围
        min_z: 0.05 # 关心的z范围
      # 如果以图片格式读取，坐标系原点为图像右下角，向上为x,向左为y
      # 图像超过大小会裁切，不够则会以最大值100填充。图片应当为灰度图，值会被clamp到[0,100]

    local_costmap: # 局部地图配置
      cloud_sub_topic: "cloud_registered" # 用于生成局部地图的点云
      cloud_queue_size: 3 # 对输入点云进行累积的帧数
      max_radius: 4.0 # 局部地图关心的xy范围，以tf的"base"的xy为参考点
      max_relative_z: 0.5 # 局部地图关心的z相对范围，以tf的"base"的z为参考点
      min_relative_z: 0.05 # 局部地图关心的z相对范围，以tf的"base"的z为参考点