/**:
  ros__parameters:
    a_star:
      downsampled_waypoint_max_interval: 20 # 对规划后的轨迹进行降采样，降采样后路径点之间的最大间隔（以格子为单位）
      occupied_threshold: 60 # OccupancyGrid中占据值达到多少认为是障碍物

    path_optimizer:
      num_samples_per_length: 0.4 # B样条的每长度采样点个数，用于计算障碍物代价等（长度以格子为单位）
      obstable_weight: 1e-0
      length_weight: 1e-3
      smooth_weight: 1e-5