/**:
  ros__parameters:
    pcd_path: "1897translated.pcd"
    cloud_sub_topic: "cloud_registered"
    num_threads: 8
    cov_num_neighbors: 100 # 计算点的协方差矩阵时采用多少个点作为邻居
    downsample_resolution_map: 0.1 # 给先验地图降采样的voxel大小
    downsample_resolution_lidar: 0.05 # 给雷达点云降采样的voxel大小
    gicp_max_correspondence_distance: 3.0 # gicp最大匹配距离
    gicp_max_iterations: 16 # gicp最大迭代次数
    fitness_score_max_dist: 0.3 # 若与最近邻居的距离超过这个值，该点不计入fitness score
    fitness_score_threshold: 0.01 # 认为gicp结果合理的fitness score阈值
    initial_pos_x: 5.0 # 初始位置x
    initial_pos_y: 0.0 # 初始位置y
    initial_pos_z: 0.0 # 初始位置z