/**:
  ros__parameters:
    pcd_path: "1897small.pcd"
    cloud_sub_topic: "/livox/lidar/pointcloud"
    num_threads: 8
    major_part_proportion: 0.95
    cov_num_neighbors: 100
    leaf_size_map: 0.1
    leaf_size_lidar: 0.05
    gicp_max_correspondence_distance: 3.0
    gicp_max_iterations: 16
    fitness_score_max_dist: 0.3
    fitness_score_threshold: 0.01
    search_spread_interval: 4.0
    search_max_spread_num: 5