/**:
  ros__parameters:
    sub_mapping:
      # General
      num_threads: 4 # Num threads used in covariance estimation
      enable_imu: true # If true, create IMU preintegration factors
      enable_optimization: false # If false, do not submap optimization (use only odom data)

      # Keyframe update strategy
      max_num_keyframes: 15 # Maximum number of keyframes in a submap
      keyframe_update_strategy: "OVERLAP" # "DISPLACEMENT" or "OVERLAP"
      keyframe_update_min_points: 500 # If a point cloud has fewer points than this, it is not considered as a keyframe
      keyframe_update_interval_rot: 3.14 # Threshold for "DISPLACEMENT" strategy
      keyframe_update_interval_trans: 1.0 # Threshold for "DISPLACEMENT" strategy
      max_keyframe_overlap: 0.6 # Threshold for "OVERLAP" strategy

      # Relative pose factors
      create_between_factors: false # If true, create SE3 relative pose factors between consecutive frames (i.e., odom_factor)
      between_registration_type: "VGICP" # Registration factor type for information matrix evaluation of relative pose factors ("NONE" / "GICP")

      # Registration error factors
      registration_error_factor_type: "VGICP" # Registration factor type for matching cost minimization (Only VGICP supported)
      keyframe_randomsampling_rate: 1.0 # Random sampling rate for registration error factors (1.0 = use all points)
      keyframe_voxel_resolution: 0.25 # Voxel resolution for registration error factors
      keyframe_voxelmap_levels: 2 # Multi-resolution voxelmap levels (must be >= 1)
      keyframe_voxelmap_scaling_factor: 2.0 # Multi-resolution voxelmap scaling factor

      # Post processing
      submap_downsample_resolution: 0.3 # Resolution of voxel grid downsampling for created submaps
      submap_target_num_points: 50000 # Downsampling target number of points for created submaps (disabled when < 0)