/**:
  ros__parameters:
    sensors:
      # IMU
      imu_upright: true # True for ENU, false for NED
      imu_acc_noise: 0.05 # Accelerometer noise
      imu_gyro_noise: 0.02 # Gyroscope noise
      imu_int_noise: 0.001 # Integration noise
      imu_bias: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] # IMU bias
      imu_bias_noise: 0.00001 # Bias randomwalk noise
      imu_acc_saturation_thresh: 235.0 # Accelerometer saturation threshold (m/s^2)
      imu_gyro_saturation_thresh: 34.5 # Gyroscope saturation threshold (rad/s)
      imu_saturation_mult: 1.0 # Covariance multiplier when saturated

      # LiDAR
      global_shutter_lidar: false # If true, fill per-point timestamps with zero and disable points deskewing
      T_lidar_imu: [-0.09873, -0.02404, 0.11875, 0.99978, -0.00695, -0.01790, -0.00786] # LiDAR-IMU transformation (xyz, xyzw)
      intensity_field: "intensity" # Field name used for extracting point intensity from PointCloud2 message
      ring_field: "line" # Field name used for extracting ring number (laser ID) from PointCloud2 message
      autoconf_perpoint_times: true # If true, automatically configure per-point timestamps. If false, use the following settings.