/**:
  ros__parameters:
    mapping:
      # Output
      save_raw_mapping_frames: true
      output_root: "."

      # Keyframe selection (relative to last keyframe)
      keyframe_trans_thresh: 1.0
      keyframe_rot_thresh: 1.0

      # Incremental map integration
      downsample_every_n_keyframes: 10000
      map_voxel_leaf_size: 0.05