/**:
  ros__parameters:
    odometry_estimation:
      # Initialization
      use_init_world_imu: false # If true, parameter init_T_world_imu and init_v_world_imu should be given instead of estimated
      init_pose_damping_scale: 1e10 # Damping scale for the initial pose (to fix the gauge freedom)
      initialization_window_size: 3.0 # Initialization window size for the "LOOSE" initialization mode [sec]
      
      # Optimization
      smoother_lag: 5.0 # Fixed-lag smoothing window size [sec]
      use_isam2_dogleg: false # Use the dogleg optimizer as the backend of ISAM2 that is slow but more robust
      isam2_relinearize_skip: 1 # Relinearization is performed every $isam2_relinearize_skip optimization calls
      isam2_relinearize_thresh: 0.1 # Relinearization is performed only when linear delta gets larger than this
      fix_imu_bias: false # If true, disable IMU bias estimation and use the initial IMU bias

      # GICP params
      correspondence_distance: 1.0 # Max correspondence distance for GICP
      full_connection_window_size: 2 # Latest sensor pose variable is connected with all of the past $full_connection_window_size poses

      # Keyframe params
      keyframe_update_strategy: "DISPLACEMENT" # "DISPLACEMENT" / "ENTROPY"
      max_num_keyframes: 5 # Maximum number of keyframes
      keyframe_delta_trans: 2.0 # Keyframe displacement threshold [m]
      keyframe_delta_rot: 0.5 # Keyframe displacement threshold [rad]
      keyframe_entropy_thresh: 0.99 # Entropy threshold

      # MISC
      save_imu_rate_trajectory: true # If true, save the IMU rate trajectory
      num_threads: 8 # Number of threads for odometry estimation