/**:
  ros__parameters:
    mpc:
      model: # 预测模型参数，基于系统辨识得到。v使用ARX模型，w使用简单的一阶滞后模型。
        # v(k+1) = sum_{i=0..n-1} v_ar[i] * v(k-i) + v_w_coeff*w(k) + v_vcmd_z1_coeff*v_cmd(k-1)
        v_order: 3
        v_ar: [1.4624857422962547, -0.25562932717008396, -0.2733356701471305]
        v_w_coeff: 0.0
        v_vcmd_z1_coeff: 0.06063408650712617
        # w(k+1) = w_alpha*w(k) + w_beta*w_cmd(k-1)
        w_alpha: -0.020247517979703505
        w_beta: 1.0202475179797035