/**:
  ros__parameters:
    direction_map_sub_topic: "/map_server/direction_map"
    cost_map_sub_topic: "/map_server/cost_map"
    goal_sub_topic: "/path_planner/goal"
    path_pub_topic: "/path_planner/path"
    plan_freq: 10 # 规划路径的频率，单位Hz

    path_planner:
      direction_weight: 2.0 # 方向代价权重
      obstacle_weight: 1.0 # 障碍物代价权重
      downsampled_waypoint_max_interval: 5 # 对规划后的轨迹进行降采样，降采样后路径点之间的最大间隔（以格子为单位）
      occupied_threshold: 200 # 超过该阈值的格子被视为不可通行

    path_optimizer:
      smoothness_weight: 0.05 # 平滑代价权重
      length_weight: 0.1 # 长度代价权重
      obstacle_weight: 2.0 # 障碍物代价权重
      direction_weight: 3.0 # 方向代价权重
      num_samples_per_length: 1.5 # 每长度采样点个数，用于计算障碍物代价等（长度以格子为单位）
      max_iterations: 50 # 优化的最大迭代次数